# TEST version of infra for FukuAuth
# Using Mongo as main database
---
services:
  mongo_test:
    image: mongo:8.0
    container_name: test_fukuauth_mongo
    command:
      - "--auth"
    ports:
      - "27018:27017"
    volumes:
      - ./database/mongo/db_test:/data/db
      - ./database/mongo/scripts/test/createDB.js:/docker-entrypoint-initdb.d/createDB.js
      - ./database/mongo/scripts/test/createUser.js:/docker-entrypoint-initdb.d/createUser.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSW:-admin}
    networks:
      - test_fuku_network

networks:
  test_fuku_network:
    name: test_fuku_network
    driver: bridge
